using Microsoft.EntityFrameworkCore.Migrations;

namespace AppSystem.Migrations
{
    public partial class DatabaseSeeds : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Afghanistan', '+93')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Albania', '+355')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Algeria', '+213')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('American Samoa', '+1-684')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Andorra', '+376')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Angola', '+244')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Anguilla', '+1-264')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Antarctica', '+672')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Antigua and Barbuda', '+1-268')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Argentina', '+54')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Armenia', '+374')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Aruba', '+297')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Australia', '+61')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Austria', '+43')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Azerbaijan', '+994')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bahamas', '+1-242')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bahrain', '+973')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bangladesh', '+880')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Barbados', '+1-246')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Belarus', '+375')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Belgium', '+32')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Belize', '+501')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Benin', '+229')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bermuda', '+1-441')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bhutan', '+975')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bolivia', '+591')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bosnia and Herzegovina', '+387')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Botswana', '+267')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bouvet Island', '+47')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Brazil', '+55')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('British Indian Ocean Territory', '+246')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Brunei Darussalam', '+673')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Bulgaria', '+359')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Burkina Faso', '+226')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Burundi', '+257')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cambodia', '+855')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cameroon', '+237')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Canada', '+1')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cape Verde', '+238')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cayman Islands', '+1-345')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Central African Republic', '+236')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Chad', '+235')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Chile', '+56')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('China', '+86')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Christmas Island', '+61')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cocos (Keeling) Islands', '+61')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Colombia', '+57')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Comoros', '+269')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Democratic Republic of the Congo', '+243')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Republic of Congo', '+243')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cook Islands', '+682')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Costa Rica', '+506')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Croatia (Hrvatska)', '+385')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cuba', '+53')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Cyprus', '+357')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Czech Republic', '+420')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Denmark', '+45')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Djibouti', '+253')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Dominica', '+1-767')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Dominican Republic', '+1-809')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('East Timor', '+670')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Ecuador', '+593')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Egypt', '+20')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('El Salvador', '+503')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Equatorial Guinea', '+240')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Eritrea', '+291')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Estonia', '+372')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Ethiopia', '+251')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Falkland Islands (Malvinas)', '+500')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Faroe Islands', '+298')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Fiji', '+679')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Finland', '+358')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('France', '+33')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('France, Metropolitan', '+249')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('French Guiana', '+254')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('French Polynesia', '689')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('French Southern Territories', '+260')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Gabon', '+241')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Gambia', '+220')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Georgia', '+995')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Germany', '+49')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Ghana', '+233')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Gibraltar', '+350')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Guernsey', '+44-1481')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Greece', '+30')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Greenland', '+299')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Grenada', '+1-473')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Guadeloupe', '+590')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Guam', '+1-671')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Guatemala', '+502')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Guinea', '+224')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Guinea-Bissau', '+245')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Guyana', '+592')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Haiti', '+509')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Heard and Mc Donald Islands', '')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Honduras', '+504')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Hong Kong', '+852')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Hungary', '+36')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Iceland', '+354')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('India', '+91')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Isle of Man', '+44-1624')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Indonesia', '+62')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Iran', '+98')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Iraq', '+964')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Ireland', '+353')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Israel', '+972')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Italy', '+39')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Ivory Coast', '+225')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Jersey', '+44-1534')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Jamaica', '+1-876')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Japan', '+81')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Jordan', '+962')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Kazakhstan', '+7')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Kenya', '+254')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Kiribati', '+686')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('North Korea', '+850')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('South Korea', '+82')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Kosovo', '+383')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Kuwait', '+965')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Kyrgyzstan', '+996')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Laos', '+856')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Latvia', '+371')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Lebanon', '+961')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Lesotho', '+266')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Liberia', '+231')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Libya', '+218')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Liechtenstein', '+423')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Lithuania', '+370')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Luxembourg', '+352')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Macau', '+853')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('North Macedonia', '+389')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Madagascar', '+261')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Malawi', '+265')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Malaysia', '+60')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Maldives', '+960')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Mali', '+223')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Malta', '+356')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Marshall Islands', '+692')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Martinique', '+258')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Mauritania', '+222')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Mauritius', '+230')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Mayotte', '+262')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Mexico', '+52')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Micronesia', '+691')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Moldova', '+373')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Monaco', '+377')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Mongolia', '+976')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Montenegro', '+382')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Montserrat', '+1-664')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Morocco', '+212')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Mozambique', '+258')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Myanmar', '+95')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Namibia', '+264')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Nauru', '+674')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Nepal', '+977')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Netherlands', '+31')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Netherlands Antilles', '+599')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('New Caledonia', '+687')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('New Zealand', '+64')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Nicaragua', '+505')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Niger', '+227')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Nigeria', '+234')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Niue', '+683')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Norfolk Island', '+672')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Northern Mariana Islands', '+1-670')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Norway', '+47')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Oman', '+968')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Pakistan', '+92')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Palau', '+680')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Palestine', '+970')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Panama', '+507')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Papua New Guinea', '+675')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Paraguay', '+595')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Peru', '+51')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Philippines', '+63')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Pitcairn', '+64')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Poland', '+48')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Portugal', '+351')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Puerto Rico', '+1-787')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Qatar', '+974')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Reunion', '+262')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Romania', '+40')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Russian', '+7')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Rwanda', '+250')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Saint Kitts and Nevis', '+1-869')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Saint Lucia', '+1-758')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Saint Vincent and the Grenadines', '+1-784')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Samoa', '+685')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('San Marino', '+378')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Sao Tome and Principe', '+239')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Saudi Arabia', '+966')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Senegal', '+221')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Serbia', '+381')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Seychelles', '+248')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Sierra Leone', '+232')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Singapore', '+65')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Slovakia', '+421')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Slovenia', '+386')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Solomon Islands', '+677')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Somalia', '+252')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('South Africa', '+27')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('South Georgia South Sandwich Islands', '+500')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('South Sudan', '+211')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Spain', '+34')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Sri Lanka', '+94')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('St. Helena', '+290')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('St. Pierre and Miquelon', '+508')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Sudan', '+249')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Suriname', '+597')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Svalbard and Jan Mayen Islands', '+47')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Swaziland', '+268')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Sweden', '+46')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Switzerland', '+41')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Syria', '+963')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Taiwan', '+886')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Tajikistan', '+992')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Tanzania', '+255')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Thailand', '+66')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Togo', '+228')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Tokelau', '+690')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Tonga', '+676')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Trinidad and Tobago', '+1-868')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Tunisia', '+216')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Turkey', '+90')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Turkmenistan', '+993')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Turks and Caicos Islands', '+1-649')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Tuvalu', '+688')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Uganda', '+256')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Ukraine', '+380')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('United Arab Emirates', '+971')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('United Kingdom', '+44')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('United States', '+1')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('United States minor outlying islands', '+246')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Uruguay', '+598')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Uzbekistan', '+998')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Vanuatu', '+678')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Vatican', '+379')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Venezuela', '+58')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Vietnam', '+84')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Virgin Islands (British)', '+1-284')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Virgin Islands (U.S.)', '+1-340')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Wallis and Futuna Islands', '+681')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Western Sahara', '+212')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Yemen', '+967')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Zambia', '+260')");
            migrationBuilder.Sql("INSERT INTO countries (Name, CountryCode) VALUES ('Zimbabwe', '+263')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        migrationBuilder.Sql("Delete From countries");
        }
    }
}
